name: svg2iv_gui
description: A simple GUI for svg2iv.
version: 0.0.0-dev

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  collection: ^1.17.2
  dynamic_color: ^1.6.6
  flutter_bloc: ^8.1.3
  path: ^1.8.3
  path_provider: ^2.1.0
  svg2iv_common:
    path: ../common
  svg2iv_common_flutter:
    path: ../common_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: ^7.0.0
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - res/icons/
