name: svg2iv_gui
description: A simple GUI for svg2iv.
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  collection: ^1.17.1
  dynamic_color: ^1.6.5
  flutter_bloc: ^8.1.3
  path: ^1.8.3
  path_provider: ^2.0.15
  svg2iv_common:
    path: ../common
  svg2iv_common_flutter:
    path: ../common_flutter
  tuple: ^2.0.1
  vector_graphics: ^1.1.7
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: ^6.1.4
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - res/icons
