name: svg2iv_gui
description: A simple GUI for svg2iv.
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  collection: ^1.16.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.5
  path: ^1.8.2
  path_provider: ^2.0.11
  svg2iv_common:
    path: ../common
  tuple: ^2.0.1
  vector_math: ^2.1.2

dev_dependencies:
  # flutter_test:
    # sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/convert_vector.svg
    - assets/destination_directory.svg
    - assets/explore_files.svg
    - assets/logo.svg
    - assets/source_files.svg
    - assets/toggle_theme.svg
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/jetbrains_mono_regular.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans_variable.ttf
