name: svg2iv_gui
description: A simple GUI for svg2iv.
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  path_provider: ^2.0.10
  svg2iv_common:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/jetbrains_mono_regular.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans_variable.ttf
