include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/protobuf/image_vector.pb.dart
    - lib/protobuf/image_vector.pbenum.dart
    - lib/protobuf/image_vector.pbjson.dart
    - lib/protobuf/image_vector.pbserver.dart
