name: svg2iv
description: A command-line application to convert SVG files to Jetpack Compose `ImageVector`s.
# version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.0
  async: ^2.11.0
  cbor: ^5.1.2
  svg2iv_common:
    path: ../common

dev_dependencies:
  lints: ^2.0.1
  # test: ^1.24.0
