name: svg2iv
description: A command-line application to convert SVG files to Jetpack Compose `ImageVector`s.
# version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.1.1
  path_parsing: ^1.0.0
  protobuf: ^2.0.0
  svg2iv_common:
    path: ../common
  tuple: ^2.0.0-nullsafety.0
  xml: ^5.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
