name: svg2iv
description: A command-line application to convert SVG files to Jetpack Compose `ImageVector`s.
# version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.1.1
  async: ^2.8.2
  svg2iv_common:
    path: ../common

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
