int? getCssColorValue(String colorName) {
  switch (colorName) {
    case 'aliceblue':
      return 0xFFF0F8FF;
    case 'antiquewhite':
      return 0xFFFAEBD7;
    case 'aqua':
    case 'cyan':
      return 0xFF00FFFF;
    case 'aquamarine':
      return 0xFF7FFFD4;
    case 'azure':
      return 0xFFF0FFFF;
    case 'beige':
      return 0xFFF5F5DC;
    case 'bisque':
      return 0xFFFFE4C4;
    case 'black':
      return 0xFF000000;
    case 'blanchedalmond':
      return 0xFFFFEBCD;
    case 'blue':
      return 0xFF0000FF;
    case 'blueviolet':
      return 0xFF8A2BE2;
    case 'brown':
      return 0xFFA52A2A;
    case 'burlywood':
      return 0xFFDEB887;
    case 'cadetblue':
      return 0xFF5F9EA0;
    case 'chartreuse':
      return 0xFF7FFF00;
    case 'chocolate':
      return 0xFFD2691E;
    case 'coral':
      return 0xFFFF7F50;
    case 'cornflowerblue':
      return 0xFF6495ED;
    case 'cornsilk':
      return 0xFFFFF8DC;
    case 'crimson':
      return 0xFFDC143C;
    case 'darkblue':
      return 0xFF00008B;
    case 'darkcyan':
      return 0xFF008B8B;
    case 'darkgoldenrod':
      return 0xFFB8860B;
    case 'darkgray':
    case 'darkgrey':
      return 0xFFA9A9A9;
    case 'darkgreen':
      return 0xFF006400;
    case 'darkkhaki':
      return 0xFFBDB76B;
    case 'darkmagenta':
      return 0xFF8B008B;
    case 'darkolivegreen':
      return 0xFF556B2F;
    case 'darkorange':
      return 0xFFFF8C00;
    case 'darkorchid':
      return 0xFF9932CC;
    case 'darkred':
      return 0xFF8B0000;
    case 'darksalmon':
      return 0xFFE9967A;
    case 'darkseagreen':
      return 0xFF8FBC8F;
    case 'darkslateblue':
      return 0xFF483D8B;
    case 'darkslategray':
    case 'darkslategrey':
      return 0xFF2F4F4F;
    case 'darkturquoise':
      return 0xFF00CED1;
    case 'darkviolet':
      return 0xFF9400D3;
    case 'deeppink':
      return 0xFFFF1493;
    case 'deepskyblue':
      return 0xFF00BFFF;
    case 'dimgray':
    case 'dimgrey':
      return 0xFF696969;
    case 'dodgerblue':
      return 0xFF1E90FF;
    case 'firebrick':
      return 0xFFB22222;
    case 'floralwhite':
      return 0xFFFFFAF0;
    case 'forestgreen':
      return 0xFF228B22;
    case 'fuchsia':
    case 'magenta':
      return 0xFFFF00FF;
    case 'gainsboro':
      return 0xFFDCDCDC;
    case 'ghostwhite':
      return 0xFFF8F8FF;
    case 'gold':
      return 0xFFFFD700;
    case 'goldenrod':
      return 0xFFDAA520;
    case 'gray':
    case 'grey':
      return 0xFF808080;
    case 'green':
      return 0xFF008000;
    case 'greenyellow':
      return 0xFFADFF2F;
    case 'honeydew':
      return 0xFFF0FFF0;
    case 'hotpink':
      return 0xFFFF69B4;
    case 'indianred':
      return 0xFFCD5C5C;
    case 'indigo':
      return 0xFF4B0082;
    case 'ivory':
      return 0xFFFFFFF0;
    case 'khaki':
      return 0xFFF0E68C;
    case 'lavender':
      return 0xFFE6E6FA;
    case 'lavenderblush':
      return 0xFFFFF0F5;
    case 'lawngreen':
      return 0xFF7CFC00;
    case 'lemonchiffon':
      return 0xFFFFFACD;
    case 'lightblue':
      return 0xFFADD8E6;
    case 'lightcoral':
      return 0xFFF08080;
    case 'lightcyan':
      return 0xFFE0FFFF;
    case 'lightgoldenrodyellow':
      return 0xFFFAFAD2;
    case 'lightgray':
    case 'lightgrey':
      return 0xFFD3D3D3;
    case 'lightgreen':
      return 0xFF90EE90;
    case 'lightpink':
      return 0xFFFFB6C1;
    case 'lightsalmon':
      return 0xFFFFA07A;
    case 'lightseagreen':
      return 0xFF20B2AA;
    case 'lightskyblue':
      return 0xFF87CEFA;
    case 'lightslategray':
    case 'lightslategrey':
      return 0xFF778899;
    case 'lightsteelblue':
      return 0xFFB0C4DE;
    case 'lightyellow':
      return 0xFFFFFFE0;
    case 'lime':
      return 0xFF00FF00;
    case 'limegreen':
      return 0xFF32CD32;
    case 'linen':
      return 0xFFFAF0E6;
    case 'maroon':
      return 0xFF800000;
    case 'mediumaquamarine':
      return 0xFF66CDAA;
    case 'mediumblue':
      return 0xFF0000CD;
    case 'mediumorchid':
      return 0xFFBA55D3;
    case 'mediumpurple':
      return 0xFF9370DB;
    case 'mediumseagreen':
      return 0xFF3CB371;
    case 'mediumslateblue':
      return 0xFF7B68EE;
    case 'mediumspringgreen':
      return 0xFF00FA9A;
    case 'mediumturquoise':
      return 0xFF48D1CC;
    case 'mediumvioletred':
      return 0xFFC71585;
    case 'midnightblue':
      return 0xFF191970;
    case 'mintcream':
      return 0xFFF5FFFA;
    case 'mistyrose':
      return 0xFFFFE4E1;
    case 'moccasin':
      return 0xFFFFE4B5;
    case 'navajowhite':
      return 0xFFFFDEAD;
    case 'navy':
      return 0xFF000080;
    case 'oldlace':
      return 0xFFFDF5E6;
    case 'olive':
      return 0xFF808000;
    case 'olivedrab':
      return 0xFF6B8E23;
    case 'orange':
      return 0xFFFFA500;
    case 'orangered':
      return 0xFFFF4500;
    case 'orchid':
      return 0xFFDA70D6;
    case 'palegoldenrod':
      return 0xFFEEE8AA;
    case 'palegreen':
      return 0xFF98FB98;
    case 'paleturquoise':
      return 0xFFAFEEEE;
    case 'palevioletred':
      return 0xFFDB7093;
    case 'papayawhip':
      return 0xFFFFEFD5;
    case 'peachpuff':
      return 0xFFFFDAB9;
    case 'peru':
      return 0xFFCD853F;
    case 'pink':
      return 0xFFFFC0CB;
    case 'plum':
      return 0xFFDDA0DD;
    case 'powderblue':
      return 0xFFB0E0E6;
    case 'purple':
      return 0xFF800080;
    case 'rebeccapurple':
      return 0xFF663399;
    case 'red':
      return 0xFFFF0000;
    case 'rosybrown':
      return 0xFFBC8F8F;
    case 'royalblue':
      return 0xFF4169E1;
    case 'saddlebrown':
      return 0xFF8B4513;
    case 'salmon':
      return 0xFFFA8072;
    case 'sandybrown':
      return 0xFFF4A460;
    case 'seagreen':
      return 0xFF2E8B57;
    case 'seashell':
      return 0xFFFFF5EE;
    case 'sienna':
      return 0xFFA0522D;
    case 'silver':
      return 0xFFC0C0C0;
    case 'skyblue':
      return 0xFF87CEEB;
    case 'slateblue':
      return 0xFF6A5ACD;
    case 'slategray':
    case 'slategrey':
      return 0xFF708090;
    case 'snow':
      return 0xFFFFFAFA;
    case 'springgreen':
      return 0xFF00FF7F;
    case 'steelblue':
      return 0xFF4682B4;
    case 'tan':
      return 0xFFD2B48C;
    case 'teal':
      return 0xFF008080;
    case 'thistle':
      return 0xFFD8BFD8;
    case 'tomato':
      return 0xFFFF6347;
    case 'turquoise':
      return 0xFF40E0D0;
    case 'violet':
      return 0xFFEE82EE;
    case 'wheat':
      return 0xFFF5DEB3;
    case 'white':
      return 0xFFFFFFFF;
    case 'whitesmoke':
      return 0xFFF5F5F5;
    case 'yellow':
      return 0xFFFFFF00;
    case 'yellowgreen':
      return 0xFF9ACD32;
    default:
      return null;
  }
}
