name: svg2iv_common_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  svg2iv_common:
    path: ../common
  vector_graphics: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - res/icons/
    - res/fonts/JetBrainsMono/OFL.txt
    - res/fonts/NotoSans/OFL.txt
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: res/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: res/fonts/NotoSans/NotoSans-Regular.ttf
        - asset: res/fonts/NotoSans/NotoSans-Medium.ttf
          weight: 500
