name: svg2iv_common
# description: TODO
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  vector_math: ^2.1.1

dev_dependencies:
  lints: ^1.0.1
