name: svg2iv_common

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  equatable: ^2.0.5
  meta: ^1.9.1
  path_parsing: ^1.0.1
  vector_graphics_compiler: ^1.1.7
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
