name: svg2iv_common
# description: TODO
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  path_parsing: ^1.0.0
  tuple: ^2.0.0
  vector_math: ^2.1.1
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.9
