name: svg2iv_common
# description: TODO
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  meta: ^1.9.1
  path_parsing: ^1.0.1
  vector_graphics_codec: ^1.1.6
  vector_graphics_compiler: ^1.1.6
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
