name: svg2iv_common
# description: TODO
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  csslib: ^0.17.1
  meta: ^1.3.0
  path_parsing: ^1.0.0
  tuple: ^2.0.0-nullsafety.0
  vector_math: ^2.1.1
  xml: ^5.3.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
