name: svg2iv_common
# description: TODO
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0
  path_parsing: ^1.0.1
  tuple: ^2.0.1
  vector_graphics_codec: ^1.1.5
  vector_graphics_compiler: ^1.1.5
  vector_math: ^2.1.4
  xml: ^6.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
