name: svg2iv_web
description: A simple web app for svg2iv.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dropzone: ^3.0.6
  stream_transform: ^2.1.0
  svg2iv_common:
    path: ../common
  svg2iv_common_flutter:
    path: ../common_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
