name: svg2iv_web
description: A simple web app for svg2iv.
# version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  svg2iv_common:
    path: ../common
  svg2iv_common_flutter:
    path: ../common_flutter
  vector_graphics: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
